spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Wustzdy_sql
    username: root
    password: zdy110629
#  liquibase:
#    change-log: classpath:user-changelog.xml
#    enabled: tr
mysql:
  iam:
    liquibaseDataSource:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Wustzdy_sql?createDatabaseIfNotExist=true
      username: root
      password: zdy110629
      maxPoolSize: 2
      connectionTimeOut: 10000
      maxLifeTime: 600000


server:
  port: 8004